# Ubuntu 16.04 does not provide python2,
# which is needed by ansible to "gather facts"
# see https://github.com/ansible/ansible/issues/16884
- name: update cache
  become: True
  raw: apt-get update

- name: Install python27
  become: True
  raw: apt-get -y install python-minimal

- name: Install aptitude
  become: True
  raw: apt-get -y install aptitude
